name: alberthon
channels:
  - conda-forge
  - microsoft
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.12.1=pyhcf101f3_0
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - distro=1.9.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h38cb7af_0
  - idna=3.11=pyhd8ed1ab_0
  - jiter=0.12.0=py311h0f0954d_1
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - liblzma=5.8.1=h39f12f2_2
  - libsqlite=3.51.2=h1ae2325_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openai=2.15.0=pyhd8ed1ab_0
  - openssl=3.6.0=h5503f6c_0
  - pip=25.3=pyh8b19718_0
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py311h71babbd_1
  - python=3.11.14=h18782d2_2_cpython
  - python_abi=3.11=8_cp311
  - readline=8.3=h46df422_0
  - setuptools=80.9.0=pyhff2d567_0
  - sniffio=1.3.1=pyhd8ed1ab_2
  - tk=8.6.13=h892fb3f_3
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - annotated-doc==0.0.4
      - bcrypt==3.2.0
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - fastapi==0.128.0
      - gitingest==0.3.1
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - loguru==0.7.3
      - markupsafe==3.0.3
      - passlib==1.7.4
      - pathspec==1.0.3
      - pycparser==2.23
      - python-dotenv==1.2.1
      - python-multipart==0.0.21
      - regex==2026.1.15
      - requests==2.32.5
      - six==1.17.0
      - sqlalchemy==2.0.45
      - starlette==0.50.0
      - tiktoken==0.12.0
      - urllib3==2.6.3
      - uvicorn==0.40.0
